/**
 * ATMOS Solana Client — TypeScript Integration
 * Bridges backend verification queue to Solana smart contract
 */

import { Program, AnchorProvider, web3, BN, Wallet } from '@project-serum/anchor';
import {
  Connection,
  PublicKey,
  Keypair,
  Transaction,
  sendAndConfirmTransaction,
  LAMPORTS_PER_SOL,
} from '@solana/web3.js';
import {
  getAssociatedTokenAddress,
  TOKEN_PROGRAM_ID,
  createAssociatedTokenAccountInstruction,
} from '@solana/spl-token';
import { logger } from '../utils/logger';

/**
 * IDL (Interface Definition Language) - stub
 * In production: import from lib.rs generation or JSON file
 */
const ATMOS_IDL = {
  version: '0.1.0',
  name: 'atmos_protocol',
  // Full IDL would be here - generated by anchor build
};

export interface MintResult {
  txHash: string;
  tokensMinted: number;
  fee: number;
  recipient: string;
  timestamp: number;
}

export interface VerificationRecordData {
  projectId: string;
  amount: number;
  zkProofHash: Buffer;
  mintedAt: number;
  recipient: string;
  status: string;
}

export class AtmosClient {
  private program: Program | null = null;
  private connection: Connection;
  private payer: Keypair | null = null;
  private programId: PublicKey;
  private mint: PublicKey;
  private feeRecipient: PublicKey;

  constructor() {
    const rpcUrl = process.env.SOLANA_RPC_URL || 'https://api.devnet.solana.com';
    this.connection = new Connection(rpcUrl, 'confirmed');

    this.programId = new PublicKey(
      process.env.SOLANA_PROGRAM_ID || 'AtmosXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    );

    this.mint = new PublicKey(
      process.env.SOLANA_MINT_ADDRESS || 'TokenkegQfeZyiNwAJsyFbPVwwP37PrLn3zYsU3qWd'
    );

    this.feeRecipient = new PublicKey(
      process.env.SOLANA_FEE_RECIPIENT || '9Z5jqg7mfFJR7mP8sZhFYxcXVNcNLyTKPEwgtzVLZvMp'
    );

    this.initializeProgram();
  }

  private initializeProgram() {
    if (process.env.NODE_ENV !== 'production') {
      logger.warn('Solana client in non-production mode');
      return;
    }

    try {
      const secretKeyStr = process.env.SOLANA_PAYER_KEY;
      if (!secretKeyStr) {
        logger.error('SOLANA_PAYER_KEY not configured');
        return;
      }

      const secretKey = JSON.parse(secretKeyStr);
      this.payer = Keypair.fromSecretKey(new Uint8Array(secretKey));

      const provider = new AnchorProvider(
        this.connection,
        new Wallet(this.payer),
        { commitment: 'confirmed' }
      );

      // In production: load real IDL from generated file
      // this.program = new Program(ATMOS_IDL as any, this.programId, provider);
      logger.info('Solana client initialized', {
        network: process.env.SOLANA_RPC_URL,
        program: this.programId.toBase58(),
        payer: this.payer.publicKey.toBase58(),
      });
    } catch (err) {
      logger.error('Failed to initialize Solana client', {
        error: (err as any).message,
      });
    }
  }

  /**
   * Mint carbon credits on Solana after backend verification
   * Called from verification queue after ZK proof generated
   */
  async mintCarbonCredits(
    projectId: string,
    amount: number,
    zkProof: Buffer,
    recipientWalletAddress: string
  ): Promise<MintResult> {
    if (!this.payer || !this.program) {
      throw new Error('Solana client not initialized');
    }

    logger.info('Minting carbon credits on Solana', {
      projectId,
      amount,
      recipient: recipientWalletAddress,
    });

    try {
      const recipientWallet = new PublicKey(recipientWalletAddress);

      // Get associated token accounts
      const recipientATA = await getAssociatedTokenAddress(
        this.mint,
        recipientWallet,
        true // Allow off-curve
      );

      const feeRecipientATA = await getAssociatedTokenAddress(
        this.mint,
        this.feeRecipient,
        true
      );

      // Create recipient ATA if it doesn't exist
      const recipientATAInfo = await this.connection.getAccountInfo(recipientATA);
      let createATAIx = null;

      if (!recipientATAInfo) {
        createATAIx = createAssociatedTokenAccountInstruction(
          this.payer.publicKey,
          recipientATA,
          recipientWallet,
          this.mint,
          TOKEN_PROGRAM_ID
        );
      }

      // Build mint instruction
      // In production: this.program.methods.mintCarbonCredits(...)
      // For now: construct transaction manually

      const tx = new Transaction();

      if (createATAIx) {
        tx.add(createATAIx);
      }

      // Placeholder: Add actual mint instruction here
      // Requires full Anchor program integration

      // Send transaction
      const txHash = await sendAndConfirmTransaction(this.connection, tx, [this.payer]);

      const fee = Math.floor((amount * 2) / 100); // 2% fee
      const tokensActuallyMinted = amount - fee;

      logger.info('Carbon credits minted successfully', {
        projectId,
        txHash,
        tokensMinted: tokensActuallyMinted,
        fee,
      });

      return {
        txHash,
        tokensMinted: tokensActuallyMinted,
        fee,
        recipient: recipientWallet.toBase58(),
        timestamp: Date.now(),
      };
    } catch (err) {
      logger.error('Failed to mint carbon credits on Solana', {
        projectId,
        error: (err as any).message,
      });
      throw err;
    }
  }

  /**
   * Get verification record from Solana
   * Lookup by PDA: seeds [b"verification", userWallet, projectId]
   */
  async getVerificationRecord(
    projectId: string,
    userWallet: PublicKey
  ): Promise<VerificationRecordData | null> {
    try {
      const [pda] = await PublicKey.findProgramAddress(
        [
          Buffer.from('verification'),
          userWallet.toBuffer(),
          Buffer.from(projectId),
        ],
        this.programId
      );

      // In production: fetch from program
      // const record = await this.program!.account.verificationRecord.fetch(pda);
      // return record;

      logger.debug('Looked up verification record', {
        projectId,
        userWallet: userWallet.toBase58(),
        pda: pda.toBase58(),
      });

      return null; // Placeholder
    } catch (err) {
      logger.warn('Verification record not found', {
        projectId,
        error: (err as any).message,
      });
      return null;
    }
  }

  /**
   * Retire carbon credits (burn tokens)
   * Used when user retires their credits for ESG/climate action
   */
  async retireCarbonCredits(
    projectId: string,
    amount: number,
    holderWallet: PublicKey
  ): Promise<string> {
    if (!this.payer) {
      throw new Error('Solana client not initialized');
    }

    logger.info('Retiring carbon credits on Solana', {
      projectId,
      amount,
      holder: holderWallet.toBase58(),
    });

    try {
      // Get holder's token account
      const holderATA = await getAssociatedTokenAddress(this.mint, holderWallet, true);

      // Build retire instruction
      // In production: this.program.methods.retireCarbonCredits(...)

      const tx = new Transaction();

      // Placeholder: Add actual retire instruction here

      // Send transaction
      const txHash = await sendAndConfirmTransaction(this.connection, tx, [this.payer]);

      logger.info('Carbon credits retired successfully', {
        projectId,
        amount,
        txHash,
      });

      return txHash;
    } catch (err) {
      logger.error('Failed to retire carbon credits', {
        projectId,
        error: (err as any).message,
      });
      throw err;
    }
  }

  /**
   * Record settlement on-chain (marketplace trade)
   */
  async recordSettlement(
    settlementId: string,
    amount: number,
    buyer: PublicKey,
    seller: PublicKey
  ): Promise<string> {
    if (!this.payer) {
      throw new Error('Solana client not initialized');
    }

    logger.info('Recording settlement on Solana', {
      settlementId,
      amount,
      buyer: buyer.toBase58(),
      seller: seller.toBase58(),
    });

    try {
      // Build settlement instruction
      // In production: this.program.methods.recordSettlement(...)

      const tx = new Transaction();

      // Placeholder: Add actual settlement instruction here

      // Send transaction
      const txHash = await sendAndConfirmTransaction(this.connection, tx, [this.payer]);

      logger.info('Settlement recorded successfully', {
        settlementId,
        txHash,
      });

      return txHash;
    } catch (err) {
      logger.error('Failed to record settlement', {
        settlementId,
        error: (err as any).message,
      });
      throw err;
    }
  }

  /**
   * Get on-chain program configuration
   */
  async getConfig() {
    try {
      const [configPda] = await PublicKey.findProgramAddress(
        [Buffer.from('config')],
        this.programId
      );

      // In production: fetch config account
      // const config = await this.program!.account.programConfig.fetch(configPda);

      logger.info('Config fetched', {
        configPda: configPda.toBase58(),
      });

      return {
        configPda: configPda.toBase58(),
        totalMinted: 0,
        totalRetired: 0,
        paused: false,
      };
    } catch (err) {
      logger.error('Failed to get config', { error: (err as any).message });
      return null;
    }
  }

  /**
   * Health check
   */
  async healthCheck(): Promise<boolean> {
    try {
      // Check payer balance
      const balance = await this.connection.getBalance(this.payer!.publicKey);
      const isHealthy = balance > 0.1 * LAMPORTS_PER_SOL;

      logger.info('Solana health check', {
        payerBalance: (balance / LAMPORTS_PER_SOL).toFixed(2),
        healthy: isHealthy,
      });

      return isHealthy;
    } catch (err) {
      logger.error('Health check failed', { error: (err as any).message });
      return false;
    }
  }
}

// Singleton instance
let solanaClient: AtmosClient | null = null;

export function getSolanaClient(): AtmosClient {
  if (!solanaClient) {
    solanaClient = new AtmosClient();
  }
  return solanaClient;
}
