// ATMOS Design System — Exact match to reference design
const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#27AE60",
    background: "#f0f4f0",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#27AE60",
    primaryForeground: "#ffffff",
    secondary: "#2ECC71",
    secondaryForeground: "#ffffff",
    muted: "#e8f5e9",
    mutedForeground: "#4a7c59",
    accent: "#27AE60",
    accentForeground: "#ffffff",
    destructive: "#E74C3C",
    destructiveForeground: "#ffffff",
    border: "#c8e6c9",
    input: "#e8f5e9",
    success: "#27AE60",
    warning: "#F39C12",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#2ECC71",
    background: "#0C1E0C",
    foreground: "#FFFFFF",
    card: "#142814",
    cardForeground: "#FFFFFF",
    primary: "#2ECC71",
    primaryForeground: "#0C1E0C",
    secondary: "#27AE60",
    secondaryForeground: "#FFFFFF",
    muted: "#1E3A1E",
    mutedForeground: "#8BAA8B",
    accent: "#2ECC71",
    accentForeground: "#0C1E0C",
    destructive: "#E74C3C",
    destructiveForeground: "#ffffff",
    border: "#1E3D1E",
    input: "#1A3A1A",
    success: "#2ECC71",
    warning: "#F39C12",
  },
  radius: 12,
};

export default colors;
